[package]
name = "hcnet-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.67"

[lib]
name = "rust_hcnet_core"
crate-type = ["staticlib"]

[dependencies]
log = "0.4.17"
cxx = "1.0"
base64 = "0.13.0"
rustc-simple-version = "0.1.0"

# This copy of the soroban host is always enabled, and should always point to a
# version that supports hcnet-core's Config::CURRENT_LEDGER_PROTOCOL_VERSION.
# When upgrading from protocol N to N+1, this copy will therefore have its
# version advance first (to enable support for N+1) even before the network has
# voted to upgrade to it. In order to avoid divergence during such an upgrade,
# we will simultaneously enable the `prev` copy of soroban (below), continuing
# to point to the previous already-released soroban that only supported protocol
# N.

[dependencies.soroban-env-host-curr]
version = "0.0.16"
git = "https://github.com/hcnet/rs-soroban-env"
package = "soroban-env-host"
rev = "0c0cae6fa22b751e7fd95d7ce7556ac6d7b7010e"
features = ["vm"]

# This copy of the soroban host is _optional_ and only enabled during protocol
# transitions. When transitioning from protocol N to N+1, the `curr` copy
# (above) will bump its version to one that supports protocol N+1, and we will
# simultaneously enable this `prev` copy by building with
# `--feature=soroban-env-host-prev` and pointing its version and git rev to the
# last soroban released to the network that speaks protocol N. When we deploy
# this to a network running protocol N it will run on `prev` until the upgrade,
# then switch from `prev` to `curr` at the upgrade, and then in the next release
# we can turn `prev` off again.
#
# A note on `rev` hashes: When `prev` is disabled, the rust-analyzer IDE will
# still want it to point to some version of soroban just for auto-completion
# (because it builds with `--all-features`). To make this work, the `rev` spec
# below has to be different from the `rev` spec in the `curr` copy of soroban
# above. The easiest way to make this work is to just point to one git rev 
# before the rev specified for `curr`.

[dependencies.soroban-env-host-prev]
optional = true
version = "0.0.15"
git = "https://github.com/hcnet/rs-soroban-env"
package = "soroban-env-host"
rev = "0aaf89ef2de1fe1eb0fbab531017ad37ccdfd205"
features = ["vm"]

[dependencies.soroban-test-wasms]
git = "https://github.com/hcnet/rs-soroban-env"
rev = "bad318a9805cf25ae64afb5122cb37af67a2edbd"

[dependencies.cargo-lock]
git = "https://github.com/rustsec/rustsec"
rev = "dcc72b697e10a2d1e3d1ce70d7d7b0d5cbc41dc4"
features = ["dependency-tree"]

# This feature definition is implied by the optional=true line in the dep, but
# writing it out in full here cross-checks that nobody _removed_ that line.
[features]
soroban-env-host-prev = ["dep:soroban-env-host-prev"]
